services:
  api:
    image: observatorio/api-registro-femicidios
    build:
      context: .
      target: development
    volumes:
      - './package.json:/opt/project/package.json'
      - './package-lock.json:/opt/project/package-lock.json'
      - './knexfile.mjs:/opt/project/knexfile.mjs'
      - './src:/opt/project/src'
      - './bin:/opt/project/bin'
      - './spec:/opt/project/spec'
      - './migrations:/opt/project/migrations'
    ports:
      - '8080:8080'
    environment:
      - AUTH_GOOGLE_CLIENT_ID
      - AUTH_GOOGLE_CLIENT_SECRET
      - DB_CONNECTION_STRING=postgresql://vivas:nosqueremos@db:5432/observatorio-femicidios
      - SERVER_CANNONICAL_ORIGIN=http://localhost:8080

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=observatorio-femicidios
      - POSTGRES_USER=vivas
      - POSTGRES_PASSWORD=nosqueremos
