version: "3"
services:
    db:
      image: postgres
      ports:
        - "5433:5433"
      volumes:
        - ./.db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=observatorio-femicidios
        - POSTGRES_USER=vivas
        - POSTGRES_PASSWORD=nosqueremos
