version: "3.8"
services:
  api:
    image: observatorio/api-registro-femicidios
    build:
      context: .
      target: development
    volumes:
       - './src:/opt/project/src'
       - './spec:/opt/project/spec'
    ports:
      - '8080:8080'

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=observatorio-femicidios
      - POSTGRES_USER=vivas
      - POSTGRES_PASSWORD=nosqueremos
